global using System;
global using System.Collections.Generic;
global using System.Linq;
global using System.Threading;
global using System.Threading.Tasks;
global using BabyFoodChecklist.Domain.Entities;
global using BabyFoodChecklist.Domain.Enums;
global using BabyFoodChecklist.Domain.Interfaces;
global using Microsoft.EntityFrameworkCore;
